baseURL: https://trot.dale.emery.name
permalinks:
    posts: /:year/:month/:filename/
languageCode: en-us
title: Twelfth Root of Two
copyright: © 2003–2023 Dale H. Emery
disableKinds: ["posts"]
taxonomies:
    tag: tags
pygmentsUseClasses: true
markup:
    goldmark:
        renderer:
            unsafe: true
