baseURL = 'https://trot.dale.emery.name'
languageCode = 'en-us'
title = 'Twelfth Root of Two'
copyright = '© 2003–2023 Dale H. Emery'

pygmentsUseClasses = true

theme = 'Dale'

[taxonomies]
tag = 'tags'

[markup.goldmark.renderer]
unsafe = true

